### ISSUE TITLE
Story Elements

### ISSUE THREAD

**Issue by FNCRNG** [FNCRNG/Pokemon-Red-Tales-from-the-Islands#13]
# Intro
- [x] Start the game in Three Island
- [x] Head downstairs and speak to Mom, Prof. Oak comes to give you a Pokemon/Pokedex and Pokeballs
- [x] Bikers have taken over the island, Oak wants you to join him on another island to train
- [ ] Beginning of northern island is open as side area initially to catch Pokemon. A scientist is hiding in the woods and will give you an exp share
- [x] On the way to the port (south) a pair of bikers on the beach challenge you
- [ ] Oak meets you in the port and takes you to Two Island where his grandson (rival) is waiting
- [x] Upon arrival to Two Island, Oak sends you off to search for his grandson
- [x] East side of the island has some wild Pokemon, but no grandson
- [x] To get to the grandson, player must travel through Cape Brink Cave (DUNGEON, 3F) to get to cape brink where he is waiting
- [x] Once out of the dungeon rival will approach and battle ensues
- [x] Player can stay at cape brink to catch/train, or climb down to find Oak again
- [x] Rival never went back to Oak, who thinks he went to the local game corner
- [x] Game corner was blocked off by biker boss previously, who is now harassing the game corner owner
- [x] Player enters into an argument between Biker Boss, GC owner and Rival
- [ ] Turns out Biker Boss kidnapped the Owner's child, and rival wants to fight but is defeated
- [ ] Boss leaves, Oak enters and Owner pleads for player to find the girl
- [ ] Oak takes player back to Three Island to search for the girl
- [ ] All bikers are hostile now, player must go to Berry Forest where Boss is holding her
- [ ] Player defeats Boss, saves the girl, and returns her to her house where Owner is waiting (Bikers are gone now)
- [ ] From here, Oak gives you his blessing to explore on your own and take the gym challenge.

------------

## Part One: Johto (Cherrygrove City - Azalea Town & Ecruteak City)
- [ ] Now that the player is free to do as they please, One and Two Islands can be accessed
- [ ] The captain on One Island can take you to Johto, but only Johto for now (the international ferry does not travel as frequently)
- [ ] Changes to One Island
    - [ ] Expand town to be larger to work for a travel hub area
    - [ ] Add underwater cave dungeon to access Treasure beach (also made a bit bigger)
    - [ ] Make Kindle Road more mountainous and allow access via land
- [ ] Johto ferry takes player to a revamped Cherrygrove City (now with a port)
- [x] Player can travel to New Bark Town, Azalea Town via new cave path connecting route 30 & 32 and Ecruteak City via Ruins of Alph
- [ ] Violet city is off limits during first visit due to a relocation of Sudowoodo via route 32, and by evil team ( yet to be decided upon ) via route 30/route 36
- [ ] Progression past Ecruteak City is blocked by Tauros
- [ ] Progression past Azalea Town is blocked by cut trees in Ilex Forest

---------------

## Part Two (or Three): Hoenn (Dewford Town, Petalburg City, Mossdeep City, Lilycove City - Safari Zone)
- [ ] When Johto plot is completed, player has the option to go either Hoenn or Kanto (one or the other ONLY, whatever the player doesn't choose will be blocked until the region that is selected is completed) <----- THIS MEANS BRANCHING PATHS
- [ ] If the player chooses Hoenn, they are taken to Mossdeep city where Tate & Liza can be challenged. Beating them will allow surfing, however other than Lilycove city and Shoal Cave ( Maybe some new areas? ) there isn't much to explore.
- [ ] Local Hoenn Ferry can take the player to Dewford Town, Slateport City, or Petalburg City.
- [ ] Brawley is challengeable, as is Norman. Levels are similar, as player can challenge them in either order (similar to Maylene/Wake in Sinnoh)
- [ ] Access to Mauville City, Rusturf Tunnel, Fortree City and the Rustboro City Gym are blocked ( Probably blocked by hms such as rock smash or cut trees, or by scripted events by the yet to be named evil team )
- [ ] Hoenn City/town/route changes (TPD)

-----------------

## Part Three (or Two): Kanto (Vermillion City - Saffron City - Cerulean City & Celadon City/Fuchsia City )
